---
version: "3"
networks:
  gitea:
    external: false
volumes:
  gitea: null
  postgres: null
services:
  server:
    image: gitea/gitea:1.22.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    env_file:
      - .env
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=gitea
      - tsdproxy.container_port=3000
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data
    runner:
      build:
        context: ./act_runner
        dockerfile: Dockerfile
      container_name: runner
      restart: always
      networks:
        - gitea
      env_file:
        - .env
